# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.22.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1------random float between 0 and 1
a1=np.random.rand(2,3,5)
print (a1)

[[[0.87619189 0.13865293 0.5146275  0.70098887 0.95085882]
  [0.56890682 0.9360026  0.83168892 0.6870179  0.67432624]
  [0.95853097 0.0360884  0.85117858 0.79096232 0.61943609]]

 [[0.10159946 0.62908242 0.77298453 0.33932736 0.17294898]
  [0.01036076 0.86358271 0.71949634 0.25058961 0.30479394]
  [0.92755164 0.51624078 0.26989932 0.66515707 0.38654419]]]


In [4]:
# Method 2-----The randint() method takes a size parameter where you can specify the shape of an array
a=np.random.randint(50,size=(2,3,5))
print(a)

[[[22 23  1 36 18]
  [39 41 23  6 17]
  [40 16 28 42 49]]

 [[ 2 44  0 22  0]
  [26  2 14 20 47]
  [36 42 11 49 22]]]


In [5]:
# Method 3------The choice() method allows you to generate a random value based on an array of values.
a3=np.random.choice([3,1,0,6,8,9], size=(2,3,5))
print(a3)

[[[3 9 1 9 1]
  [1 1 3 8 0]
  [8 9 1 6 0]]

 [[6 6 0 1 9]
  [8 1 0 9 1]
  [8 9 3 1 9]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[22 23  1 36 18]
  [39 41 23  6 17]
  [40 16 28 42 49]]

 [[ 2 44  0 22  0]
  [26  2 14 20 47]
  [36 42 11 49 22]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.random.choice([1],size=(5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
np.size(a)==np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
np.add(a,b)

#is not possible as the SHAPE is not the same for the arrays.they must be broadcastable to a common shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=np.transpose(b,(1,2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
# mirar que al transponer b se cambia de una (5,2,3) a una (3,2,5) y queremos una (2,3,5)
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print('a=',a)
print('d=',d)

a= [[[22 23  1 36 18]
  [39 41 23  6 17]
  [40 16 28 42 49]]

 [[ 2 44  0 22  0]
  [26  2 14 20 47]
  [36 42 11 49 22]]]
d= [[[23 24  2 37 19]
  [40 42 24  7 18]
  [41 17 29 43 50]]

 [[ 3 45  1 23  1]
  [27  3 15 21 48]
  [37 43 12 50 23]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e= np.multiply(a,c)
print(e)

[[[22 23  1 36 18]
  [39 41 23  6 17]
  [40 16 28 42 49]]

 [[ 2 44  0 22  0]
  [26  2 14 20 47]
  [36 42 11 49 22]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
np.size(a)==np.size(e)
np.shape(a)==np.shape(e)
#a y b have the same size and shape(2,3,5)  so the result has the same size and shape.

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.average(d)
print(d_max,"/",d_min,"/",d_mean)

50 / 1 / 25.6


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty([2,3,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [63]:
for i in d:
    if i.any() > d_min and i.any() < d_mean:
        f[i] = 25
    if i.any() > d_mean and i.any() < d_max:
        f[i] = 75

    if i.any() == d_mean:
        f[i] = 50

    #if i.any() == d_min: #(no me funciona esta parte)
        #f[i] = 0

    if i.any() == d_max:
        f[i] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [60]:
# your code here
print('d=',d)
print('f=',f)

d= [[[23 24  2 37 19]
  [40 42 24  7 18]
  [41 17 29 43 50]]

 [[ 3 45  1 23  1]
  [27  3 15 21 48]
  [37 43 12 50 23]]]
f= [[[ 0. 24.  2. 37. 19.]
  [40. 42. 24.  7. 18.]
  [41. 17. 29. 43. 50.]]

 [[ 3. 45.  1. 23.  1.]
  [27.  3. 15. 21. 48.]
  [37. 43. 12. 50. 23.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [73]:
# your code here
for i in d:
    if i.any() > d_min and i.any() < d_mean:
        i = 'A'
        f.append(i)

    if i.any() > d_mean and i.any() < d_max:
        i = 'B'
        f.append(i)

    if i.any() == d_mean:
        i = 'C'
        f.append(i)

    #if i.any() == d_min:
        #i = 'D'
        #i.append(f)

    if i.any() == d_max:
        i = 'E'
        f.append(i)


In [74]:
print(f)

[[[ 0. 24.  2. 37. 19.]
  [40. 42. 24.  7. 18.]
  [41. 17. 29. 43. 50.]]

 [[ 3. 45.  1. 23.  1.]
  [27.  3. 15. 21. 48.]
  [37. 43. 12. 50. 23.]]]
